### ISSUE TITLE
Is it alive?

### ISSUE THREAD

**Issue by ArmorDarks** [saperio/grunt-image-size#3]
Hi

Would like to know is it still maintained. Thanks!

**Comment by ArmorDarks** [comment]
@saperio?

**Comment by saperio** [comment]
Hi! If you have any suggestions or issues, you may file an issue. But I do not actively develop this project.

**Comment by ArmorDarks** [comment]
@saperio glad to hear from you! I almost was sure that repo is dead :)

Yeap, I have few suggestions, and there are definitely few issues with current code. I could make a PR, are you up to review it?

Just to avoid useless work, here is few points we'd like to fix:

1. `require` statements should be put outside of export, for better performance
2. Types check should be removed. They causing a lot of issues, and for no reason doesn't allow to specify extension types directly in user's task configuration

   https://github.com/saperio/grunt-image-size/blob/master/tasks/image_size.js#L14

3. We'd like to add https://standardjs.com/ to make codestyle uniform. Are you ok with Standard's codestyle?
4. I would like to add ability to specify callbacks, which will preprocess or postprocess some pieces of outputted data (like paths, or object). Similar to this one: https://github.com/ArmorDarks/grunt-gray-matter#optionspreprocessmatterdata
5. We'd be glad to replace fork of `image-size` with current original branch, it seems to be quite stable.
6. Add option `baseDir` which will be stripped from outputted `name` property for each images. It is useful thing for good portion of projects. Similar to this one https://github.com/ArmorDarks/grunt-gray-matter#optionsbasedir

What do you think?

**Comment by saperio** [comment]
Your PRs are welcome. Except of Standard.

**Comment by ArmorDarks** [comment]
Great!

> Except of Standard

We can opt with other codestyle or similar tool. Standard is just the simplest one, with zero configuration (which is good) and ability to automatically format code, and it is commonly accepted.

We'd like to unify codestyle in first PR, since it is blocking and will prevent easy merge of all other PRs. Can you decide on what you'd like to see? Standard, Airbnb or Prettier? All of those right now de facto standards of codestyle in JS world.

Please, put all your feelings aside. I hope we will not boil down to tabs vs spaces discussions.

**Comment by saperio** [comment]
Prettier is quite good.

**Comment by ArmorDarks** [comment]
> Prettier is quite good.

Ok, I'll spend some time to configure it, exclusively for you :) Never dealt with it before. Anyway, it is better than no linting/formatting at all.
